{% set version = "2.28.0" %}

package:
  name: imageio
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/imageio/imageio-{{ version }}.tar.gz
  sha256: 467763bdb6e614d1ea8b4565e42c53fb2eb2fd4307a4601e97102a958c09812a
  patches:
    - tempfix-pyav-plugin.patch
    - xfail-known-issues.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
  entry_points:
    - imageio_download_bin = imageio.__main__:download_bin_main
    - imageio_remove_bin = imageio.__main__:remove_bin_main

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - numpy
    - pillow >=8.3.2

test:
  requires:
    - git
    - pytest
    - psutil
    - tifffile
    - gdal
    - astropy
    - freeimage
    - fsspec
    - requests
    - av !=10.0.0
    #- opencv
    - imageio-ffmpeg
  imports:
    - imageio
  source_files:
    - tests/
  commands:
    - imageio_download_bin -h
    - imageio_remove_bin -h
    - pytest -sv tests/ -k "not test_findlib2"

about:
  home: https://imageio.github.io
  doc_url: https://imageio.readthedocs.io
  dev_url: https://github.com/imageio/imageio
  summary: A Python library for reading and writing image data
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anjos
    - almarklein
    - blink1073
    - jni
